creation_rules:
  # Desktop Fedora
  # MK-II
  # Mac
  - age: >-
      age1y707vfysz25vyrt88uw8mlwulv0c9hq0jj9qjk4vf8m3rs3kdykqu8r0d8,
      age1g6fsucrtdvt6gnufcw9cr8t4qy33sl8rqgqq4xsa2uq2tkfdx5fseh2lsu,
      age13t99gmn3yhrzdjnhxmerue388frhrwatuj3e045lf5frxdqjputsugx7hf